version: "3.9"

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: "php"
    ports:
      - "9000:9000"
    volumes:
      - ./src/:/app
    depends_on:
      - db
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    container_name: "db"
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    container_name: "web-server"
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php
    volumes:
      - ./src/:/app


volumes:
  mysql-data: